StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E842C1157D6ACE6}" {
   Id "M113-EditableEntity_M113_APC_Name"
   Target_en_us "M113 Armored Personel Vehicle"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1585721963
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{2A87CD35D090A3E8}Prefabs/Vehicles/Tracked/M113/M113_APC_FIA.et"
  }
  CustomStringTableItem "{5E842C1157C8F77A}" {
   Id "M113-EditableEntity_M113_MEV_Name"
   Target_en_us "M113 Medical Evacuation Vehicle"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1585721940
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{953523CFE2DB9769}Prefabs/Vehicles/Tracked/M113/M113_APC_MERDC.et"
  }
  CustomStringTableItem "{5E842C1157CCA6A0}" {
   Id "M113-EditableEntity_M113A3_APC_Name"
   Target_en_us "M113A3 Armored Personel Vehicle"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1585721986
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{29FB8893F52B807B}Prefabs/Vehicles/Tracked/M113/M113A3_APC_FIA.et"
  }
  CustomStringTableItem "{5E8431794E5A1895}" {
   Id "M113-EditableEntity_M113A3_MEV_Name"
   Target_en_us "M113A3 Medical Evacuation Vehicle"
   Modified 1585722048
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
 }
}